### ISSUE TITLE
openjdk11 JAXB

### ISSUE THREAD

**Issue by Papadiddypub** [SwitchEV/RISE-V2G#57]
Java 11 has JAXB removed. Therefore compiling with maven throws an error: package javax.xml.bind does not exist.
Adding 

\<dependency>
   &nbsp;  \<groupId>javax.xml.bind\</groupId>
    &nbsp; \<artifactId>jaxb-api\</artifactId>
    &nbsp; \<version>2.3.1\</version>
\</dependency>

in \<dependencies> solved the issue.
More information can be found here:
https://www.jesperdj.com/2018/09/30/jaxb-on-java-9-10-11-and-beyond/

I did not test for downgrade compatibility

**Comment by nx518** [comment]
Thanks, I had the same issue and your hint resolved it.

**Comment by scotty1269** [comment]
Also thank you! But I needed to add this additional dependency to get all errors removed:

<dependency>
	<groupId>org.glassfish.jaxb</groupId>
	<artifactId>jaxb-runtime</artifactId>
         <version>2.3.2</version>
</dependency>
